nodeLinker: node-modules

npmScopes:
  tiptap-pro:
    npmAlwaysAuth: true
    npmAuthToken: "${REMOVED_TIPTAP_TOKEN_SEE_docs_TIPTAP_PRO_md}"
    npmRegistryServer: "https://registry.tiptap.dev/"

plugins:
  - path: .yarn/plugins/@stacks/plugin-setup.cjs
    spec: "@stacks/plugin-setup"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
