nodeLinker: node-modules

npmScopes:
  tiptap-pro:
    npmAlwaysAuth: true
    npmAuthToken: "${+QSgsewWbFUUbKhpTBNfTt0Oero9T8nH0X0aoVzhi+MoFLNB08EU+U3DPX7R56Ly}"
    npmRegistryServer: "https://registry.tiptap.dev/"

plugins:
  - path: .yarn/plugins/@stacks/plugin-setup.cjs
    spec: "@stacks/plugin-setup"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
