#!/usr/bin/env node
// Copyright (C) 2026 Cristian Barlutiu — Licensed under AGPL v3. See LICENSE.
/**
 * Build-time codegen: convert the web app's SVG sprite into a TypeScript
 * map that the mobile Icon component can render with react-native-svg's
 * `SvgXml`.
 *
 * We intentionally avoid runtime XML parsing inside the RN bundle so the
 * first Icon render is cheap — instead we extract each `<symbol>` from
 * `packages/app/src/app/icons/sprites.svg` once here and emit a static
 * TypeScript module with the inner markup already wrapped in a standalone
 * `<svg viewBox>` envelope.
 *
 * Run: `node packages/mobile/scripts/generate-icons.js`
 * Or: `yarn workspace @stacks/mobile icons:generate`.
 */

const fs = require("fs");
const path = require("path");

const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const SPRITE_PATH = path.join(
    REPO_ROOT,
    "packages",
    "app",
    "src",
    "app",
    "icons",
    "sprites.svg"
);
const OUTPUT_PATH = path.join(__dirname, "..", "src", "components", "Icon", "generated.ts");

function runAll(regex, text) {
    const results = [];
    let m;
    while ((m = regex.exec(text)) !== null) {
        results.push(m);
        if (m.index === regex.lastIndex) regex.lastIndex++;
    }
    regex.lastIndex = 0;
    return results;
}

function main() {
    const sprite = fs.readFileSync(SPRITE_PATH, "utf8");

    const symbolRe = /<symbol\b([^>]*)>([\s\S]*?)<\/symbol>/g;
    const attrRe = /([a-zA-Z_:][\w:.\-]*)\s*=\s*"([^"]*)"/g;

    const icons = {};
    for (const match of runAll(symbolRe, sprite)) {
        const [, attrs, inner] = match;

        const attrMap = {};
        for (const a of runAll(attrRe, attrs)) {
            attrMap[a[1]] = a[2];
        }

        const id = attrMap.id;
        if (!id) continue;

        const viewBox = attrMap.viewBox || "0 0 24 24";
        const cleaned = inner.replace(/\s+/g, " ").trim();
        icons[id] = { viewBox, inner: cleaned };
    }

    const entries = Object.keys(icons)
        .sort()
        .map(id => {
            const { viewBox, inner } = icons[id];
            return `    ${JSON.stringify(id)}: { viewBox: ${JSON.stringify(
                viewBox
            )}, inner: ${JSON.stringify(inner)} },`;
        });

    const body = `/* eslint-disable */
/**
 * AUTO-GENERATED by packages/mobile/scripts/generate-icons.js
 * Do not edit by hand. Regenerate with \`yarn workspace @stacks/mobile icons:generate\`.
 *
 * Source: packages/app/src/app/icons/sprites.svg
 */

export interface IconSpriteEntry {
    viewBox: string;
    inner: string;
}

export const ICON_SPRITE: Readonly<Record<string, IconSpriteEntry>> = {
${entries.join("\n")}
};

export type IconName = keyof typeof ICON_SPRITE;
`;

    fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(OUTPUT_PATH, body, "utf8");

    console.log(
        `[generate-icons] Wrote ${Object.keys(icons).length} icons to ${path.relative(
            REPO_ROOT,
            OUTPUT_PATH
        )}`
    );
}

main();
